#!/bin/bash
readonly TIMEOUT=3
function checkport() (
start_time=`date +%s`
( >/dev/tcp/$1/$2) &>/dev/null
if [ $? -eq 0 ]; then
        echo "++ $1:$2 is open"
else
end_time=`date +%s`
exec_time=$((end_time-start_time))
if [ $exec_time -lt $TIMEOUT ]
 then
        echo "-- $1:$2 is closed"
fi
fi
)

filename="$1"
while IFS='' read -r line || [[ -n "$line" ]]; do
read -r -a array <<< "$line"
( checkport "${array[0]}" "${array[1]}" ) & PID=$!
disown
(sleep $TIMEOUT &&
if ps -p $PID > /dev/null
then
echo "--- ${array[0]}":"${array[1]} is closed"
kill -9 $PID
fi
)

done < "$filename"
