#!/bin/bash
readonly TIMEOUT=2
MINPORT="$2"
MAXPORT="$3"
function checkport() (
start_time=`date +%s`
( >/dev/tcp/$1/$2) &>/dev/null
if [ $? -eq 0 ]; then
        return 0
else
end_time=`date +%s`
exec_time=$((end_time-start_time))
if [ $exec_time -lt $TIMEOUT ]; then
        return 1
fi
fi
)

filename="$1"
while IFS='' read -r line || [[ -n "$line" ]]; do
read -r -a array <<< "$line"
host=${array[0]}
port=MINPORT

for (( port=MINPORT; port <=$MAXPORT; port++ ))
do
  ( (checkport $host $port)
if [ $? -eq 0 ]; then
echo " ++ $host:$port is open"
else
echo " -- $host:$port is closed"
fi
 ) & PID=$!
disown
(sleep $TIMEOUT &&
if ps -p $PID > /dev/null
then
echo "--- $host":"$port is closed"
kill -9 $PID
fi
)
done
done < "$filename"

