#!/bin/bash
function checkport() {
 ( >/dev/tcp/$1/$2) &>/dev/null
if [ $? -eq 0 ]; then
        echo "++ $1:$2 is open"
else
        echo "-- $1:$2 is closed"
fi
}
filename="$1"
while IFS='' read -r line || [[ -n "$line" ]]; do
read -r -a array <<< "$line"
checkport "${array[0]}" "${array[1]}"
done < "$filename"
